// src/redux/types.js

// Types pour les actions liées aux tirages
export const FETCH_LATEST_DRAW_REQUEST = 'FETCH_LATEST_DRAW_REQUEST';
export const FETCH_LATEST_DRAW_SUCCESS = 'FETCH_LATEST_DRAW_SUCCESS';
export const FETCH_LATEST_DRAW_FAILURE = 'FETCH_LATEST_DRAW_FAILURE';

export const FETCH_DRAW_HISTORY_REQUEST = 'FETCH_DRAW_HISTORY_REQUEST';
export const FETCH_DRAW_HISTORY_SUCCESS = 'FETCH_DRAW_HISTORY_SUCCESS';
export const FETCH_DRAW_HISTORY_FAILURE = 'FETCH_DRAW_HISTORY_FAILURE';

export const FETCH_DRAW_BY_DATE_REQUEST = 'FETCH_DRAW_BY_DATE_REQUEST';
export const FETCH_DRAW_BY_DATE_SUCCESS = 'FETCH_DRAW_BY_DATE_SUCCESS';
export const FETCH_DRAW_BY_DATE_FAILURE = 'FETCH_DRAW_BY_DATE_FAILURE';

export const FETCH_DRAW_BY_ID_REQUEST = 'FETCH_DRAW_BY_ID_REQUEST';
export const FETCH_DRAW_BY_ID_SUCCESS = 'FETCH_DRAW_BY_ID_SUCCESS';
export const FETCH_DRAW_BY_ID_FAILURE = 'FETCH_DRAW_BY_ID_FAILURE';

// Types pour les actions liées aux prédictions
export const FETCH_PREDICTIONS_REQUEST = 'FETCH_PREDICTIONS_REQUEST';
export const FETCH_PREDICTIONS_SUCCESS = 'FETCH_PREDICTIONS_SUCCESS';
export const FETCH_PREDICTIONS_FAILURE = 'FETCH_PREDICTIONS_FAILURE';

export const GENERATE_PREDICTION_REQUEST = 'GENERATE_PREDICTION_REQUEST';
export const GENERATE_PREDICTION_SUCCESS = 'GENERATE_PREDICTION_SUCCESS';
export const GENERATE_PREDICTION_FAILURE = 'GENERATE_PREDICTION_FAILURE';

export const FETCH_PREDICTION_BY_ID_REQUEST = 'FETCH_PREDICTION_BY_ID_REQUEST';
export const FETCH_PREDICTION_BY_ID_SUCCESS = 'FETCH_PREDICTION_BY_ID_SUCCESS';
export const FETCH_PREDICTION_BY_ID_FAILURE = 'FETCH_PREDICTION_BY_ID_FAILURE';

// Types pour les actions liées aux statistiques
export const FETCH_STATS_REQUEST = 'FETCH_STATS_REQUEST';
export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS';
export const FETCH_STATS_FAILURE = 'FETCH_STATS_FAILURE';

export const FETCH_NUMBER_FREQUENCIES_REQUEST = 'FETCH_NUMBER_FREQUENCIES_REQUEST';
export const FETCH_NUMBER_FREQUENCIES_SUCCESS = 'FETCH_NUMBER_FREQUENCIES_SUCCESS';
export const FETCH_NUMBER_FREQUENCIES_FAILURE = 'FETCH_NUMBER_FREQUENCIES_FAILURE';

export const FETCH_STAR_FREQUENCIES_REQUEST = 'FETCH_STAR_FREQUENCIES_REQUEST';
export const FETCH_STAR_FREQUENCIES_SUCCESS = 'FETCH_STAR_FREQUENCIES_SUCCESS';
export const FETCH_STAR_FREQUENCIES_FAILURE = 'FETCH_STAR_FREQUENCIES_FAILURE';

export const FETCH_DRAW_DAY_DISTRIBUTION_REQUEST = 'FETCH_DRAW_DAY_DISTRIBUTION_REQUEST';
export const FETCH_DRAW_DAY_DISTRIBUTION_SUCCESS = 'FETCH_DRAW_DAY_DISTRIBUTION_SUCCESS';
export const FETCH_DRAW_DAY_DISTRIBUTION_FAILURE = 'FETCH_DRAW_DAY_DISTRIBUTION_FAILURE';

// Types pour les actions liées aux grilles
export const SAVE_GRID_REQUEST = 'SAVE_GRID_REQUEST';
export const SAVE_GRID_SUCCESS = 'SAVE_GRID_SUCCESS';
export const SAVE_GRID_FAILURE = 'SAVE_GRID_FAILURE';

export const FETCH_GRIDS_REQUEST = 'FETCH_GRIDS_REQUEST';
export const FETCH_GRIDS_SUCCESS = 'FETCH_GRIDS_SUCCESS';
export const FETCH_GRIDS_FAILURE = 'FETCH_GRIDS_FAILURE';

export const DELETE_GRID_REQUEST = 'DELETE_GRID_REQUEST';
export const DELETE_GRID_SUCCESS = 'DELETE_GRID_SUCCESS';
export const DELETE_GRID_FAILURE = 'DELETE_GRID_FAILURE';

// Types pour les actions liées à l'authentification (si nécessaire)
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// Types pour les actions liées à l'interface utilisateur
export const SET_THEME = 'SET_THEME';
export const TOGGLE_THEME = 'TOGGLE_THEME';

export const SET_LANGUAGE = 'SET_LANGUAGE';

export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';

export const SET_LOADING = 'SET_LOADING';
