// src/redux/types.js

// Draw Actions
export const FETCH_LATEST_DRAWS_REQUEST = 'FETCH_LATEST_DRAWS_REQUEST';
export const FETCH_LATEST_DRAWS_SUCCESS = 'FETCH_LATEST_DRAWS_SUCCESS';
export const FETCH_LATEST_DRAWS_FAILURE = 'FETCH_LATEST_DRAWS_FAILURE';

export const FETCH_DRAW_HISTORY_REQUEST = 'FETCH_DRAW_HISTORY_REQUEST';
export const FETCH_DRAW_HISTORY_SUCCESS = 'FETCH_DRAW_HISTORY_SUCCESS';
export const FETCH_DRAW_HISTORY_FAILURE = 'FETCH_DRAW_HISTORY_FAILURE';

// Grid Actions
export const GENERATE_GRIDS_REQUEST = 'GENERATE_GRIDS_REQUEST';
export const GENERATE_GRIDS_SUCCESS = 'GENERATE_GRIDS_SUCCESS';
export const GENERATE_GRIDS_FAILURE = 'GENERATE_GRIDS_FAILURE';

export const FETCH_SAVED_GRIDS_REQUEST = 'FETCH_SAVED_GRIDS_REQUEST';
export const FETCH_SAVED_GRIDS_SUCCESS = 'FETCH_SAVED_GRIDS_SUCCESS';
export const FETCH_SAVED_GRIDS_FAILURE = 'FETCH_SAVED_GRIDS_FAILURE';

export const SAVE_GRID_REQUEST = 'SAVE_GRID_REQUEST';
export const SAVE_GRID_SUCCESS = 'SAVE_GRID_SUCCESS';
export const SAVE_GRID_FAILURE = 'SAVE_GRID_FAILURE';

export const UPDATE_GRID_REQUEST = 'UPDATE_GRID_REQUEST';
export const UPDATE_GRID_SUCCESS = 'UPDATE_GRID_SUCCESS';
export const UPDATE_GRID_FAILURE = 'UPDATE_GRID_FAILURE';

export const DELETE_GRID_REQUEST = 'DELETE_GRID_REQUEST';
export const DELETE_GRID_SUCCESS = 'DELETE_GRID_SUCCESS';
export const DELETE_GRID_FAILURE = 'DELETE_GRID_FAILURE';

// Statistics Actions
export const FETCH_STATISTICS_REQUEST = 'FETCH_STATISTICS_REQUEST';
export const FETCH_STATISTICS_SUCCESS = 'FETCH_STATISTICS_SUCCESS';
export const FETCH_STATISTICS_FAILURE = 'FETCH_STATISTICS_FAILURE';

// Prediction Actions
export const FETCH_PREDICTIONS_REQUEST = 'FETCH_PREDICTIONS_REQUEST';
export const FETCH_PREDICTIONS_SUCCESS = 'FETCH_PREDICTIONS_SUCCESS';
export const FETCH_PREDICTIONS_FAILURE = 'FETCH_PREDICTIONS_FAILURE';

// UI Actions
export const SET_THEME = 'SET_THEME';
export const TOGGLE_THEME = 'TOGGLE_THEME';
